# .bash_profile
# vim:sts=4 sw=4 et
# Bash shell per-login initialisation for ABO

# Prevent Bash from always breaking completion words on ':' so that
# account names containing ':' can be completed like usual
COMP_WORDBREAKS=${COMP_WORDBREAKS//:}

# Prevent Bash from always breaking completion words on '=' so that --select
# arguments starting with '=' can be completed as a list of tags.
COMP_WORDBREAKS=${COMP_WORDBREAKS//=}

complete -o nospace -C 'abo compa' abo

complete -F _complete_vault vault

_complete_vault() {
    COMPREPLY=()
    local cur=${COMP_WORDS[COMP_CWORD]}
    case $COMP_CWORD in
    1) COMPREPLY=( $(compgen -W 'open close' -- "$cur") );;
    2) COMPREPLY=( $(compgen -d -- "$cur") );;
    esac
}
